Fix flask.Markup import error
Using flask.Markup gives this error:

```
ImportError: cannot import name 'Markup' from 'flask'
```

According to Flask repo, this lib is deprecated and replaced by
markupsafe.Markup: https://github.com/pallets/flask/pull/4996.